version: "3"
dotenv: ['apps/api/.env']
tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  setup:
    desc: Install root and web dependencies
    cmds:
      - bun install
      - bun install --cwd apps/web

  web:dev:
    desc: Run web app in dev mode
    dir: apps/web
    cmds:
      - bun run dev

  web:build:
    desc: Build web app
    dir: apps/web
    cmds:
      - bun run build

  web:lint:
    desc: Lint web app
    dir: apps/web
    cmds:
      - bun run lint

  api:run:
    desc: Run API server
    dir: apps/api
    cmds:
      - go run ./cmd/server

  api:build:
    desc: Build API binaries
    dir: apps/api
    cmds:
      - go build ./...

  db:migrate:
    desc: Run database migrations
    dir: apps/api
    cmds:
      - migrate -path db/migrations -database "$DATABASE_URL" up

  db:rollback:
    desc: Roll back last migration
    dir: apps/api
    cmds:
      - migrate -path db/migrations -database "$DATABASE_URL" down 1

  db:status:
    desc: Check migration status
    dir: apps/api
    cmds:
      - migrate -path db/migrations -database "$DATABASE_URL" version

  db:generate:
    desc: Generate Go code from SQL queries
    dir: apps/api
    cmds:
      - sqlc generate

  db:new:
    desc: Create a new migration file
    dir: apps/api
    cmds:
      - migrate create -ext sql -dir db/migrations -seq {{.CLI_ARGS}}

  api:tidy:
    desc: Tidy Go dependencies
    dir: apps/api
    cmds:
      - go mod tidy

  build:
    desc: Build all apps
    deps:
      - api:build
      - web:build

