version: "3"

dotenv: ['apps/api/.env']

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  setup:
    desc: Install all dependencies (root + web)
    cmds:
      - bun install
      - bun install --cwd apps/web
      - task api:tidy

  web:dev:
    desc: Run web app in development
    dir: apps/web
    cmds:
      - bun run dev

  web:build:
    desc: Build web app
    dir: apps/web
    cmds:
      - bun run build

  web:lint:
    desc: Lint web app
    dir: apps/web
    cmds:
      - bun run lint

  web:typecheck:
    desc: Type-check web app
    dir: apps/web
    cmds:
      - bunx tsc --noEmit

  web:ci:
    desc: Run all web checks (lint + typecheck + build)
    deps:
      - web:lint
      - web:typecheck
      - web:build

  api:run:
    desc: Run API server
    dir: apps/api
    cmds:
      - go run ./cmd/server

  api:build:
    desc: Build API binary
    dir: apps/api
    cmds:
      - go build -o bin/server ./cmd/server

  api:tidy:
    desc: Tidy Go dependencies
    dir: apps/api
    cmds:
      - go mod tidy

  api:fmt:
    desc: Format Go code
    dir: apps/api
    cmds:
      - go fmt ./...

  api:lint:
    desc: Lint Go API
    dir: apps/api
    cmds:
      - golangci-lint run ./...

  api:test:
    desc: Run Go tests
    dir: apps/api
    cmds:
      - go test ./...

  api:coverage:
    desc: Run tests with coverage
    dir: apps/api
    cmds:
      - go test -coverprofile=coverage.out ./...

  api:ci:
    desc: Run all API checks (fmt + lint + test + build)
    deps:
      - api:fmt
      - api:lint
      - api:test
      - api:build

  db:migrate:
    desc: Run database migrations
    dir: apps/api
    cmds:
      - migrate -path db/migrations -database "$DATABASE_URL" up

  db:rollback:
    desc: Roll back last migration
    dir: apps/api
    cmds:
      - migrate -path db/migrations -database "$DATABASE_URL" down 1

  db:status:
    desc: Check migration version
    dir: apps/api
    cmds:
      - migrate -path db/migrations -database "$DATABASE_URL" version

  db:new:
    desc: Create a new migration file
    dir: apps/api
    cmds:
      - migrate create -ext sql -dir db/migrations -seq {{.CLI_ARGS}}

  db:generate:
    desc: Generate Go code from SQL (sqlc)
    dir: apps/api
    cmds:
      - sqlc generate

  build:
    desc: Build entire monorepo
    deps:
      - web:build
      - api:build

  ci:
    desc: Run all checks (web + api)
    deps:
      - web:ci
      - api:ci
